apiVersion: v1
kind: Config
current-context: development

contexts:
- name: development
  context:
    server: https://digit-lts.digit.org
    realm: ACCOUNT9
    client-id: auth-server
    client-secret: changeme
    username: test@example.com
    password: default
